#!/bin/bash
RANDSTRING=`head -c 16 /dev/random  | base64 | grep -o . | sort -R | tr -d "\n" | head -c 14`
REQCLASS1=`date | base64 | tr -dc A-Z | grep -o . | sort -R | tr -d "\n" | head -c2`
REQCLASS2=`date | base64 | tr -dc a-z | grep -o . | sort -R | tr -d "\n" | head -c2`
REQCLASS3=`date | tr -dc 0-9 | grep -o . | sort -R | tr -d "\n" | head -c2`
REQCHARS=`echo $REQCLASS1$REQCLASS2$REQCLASS3`
TEMPPASS=`echo "$RANDSTRING$REQCHARS" | grep -o . | sort -R | tr -d "\n"`
umask 0027
echo $TEMPPASS > /root/ldap.RootDNPwd
setup-ds.pl -s -f ds389setup.inf General.FullMachineName=`hostname` "General.ConfigDirectoryLdapURL=ldap://`hostname`:389/o=NetscapeRoot" slapd.RootDNPwd=$TEMPPASS
echo "Internal (Software) Token:$TEMPPASS" > /etc/dirsrv/slapd-ncsa-ldap/pin.txt
